use phf::phf_map;

#[derive(Clone, Debug)]

pub(crate) struct TextBlock {
    pub(crate) text: String,
    pub(crate) bg: String,
    pub(crate) fg: String
}

#[derive(Clone, Debug)]
pub(crate) struct RwrInfo{
    pub(crate) abrv: String,
    pub(crate) nato_name: String,
    pub(crate) rwr_code: String,
    pub(crate) rng_nm: String,
    pub(crate) rng_km: String,
    pub(crate) alt_ft: String,
    pub(crate) alt_mtr: String,
    pub(crate) flr: String,
    pub(crate) chf: String,
    pub(crate) ecm: String,
    pub(crate) lock_time: String,
    pub(crate) guidance: String,
}

pub fn rwr_info_lut(rwr_code: &str) -> RwrInfo {
    match rwr_code{
        "SA-2"      => RwrInfo   { abrv: "SA-2".to_string(),     nato_name: "GUIDELINE".to_string(),rwr_code: "2".to_string(),    rng_nm: "28.00".to_string(),   rng_km: "51,86".to_string(),    alt_ft: "82.000".to_string()    ,alt_mtr: "24.992".to_string()  ,flr: "-".to_string() ,chf: "G".to_string() ,ecm: "G".to_string() ,lock_time: "MED".to_string(), guidance: "RDR CMD".to_string()},
        "SA-3"      => RwrInfo   { abrv: "SA-3".to_string(),     nato_name: "GOA".to_string()      ,rwr_code: "3".to_string(),    rng_nm: "13.5".to_string(),    rng_km: "25".to_string(),       alt_ft: "65.600".to_string()    ,alt_mtr: "19.994".to_string()  ,flr: "-".to_string() ,chf: "Y".to_string() ,ecm: "Y".to_string() ,lock_time: "MED".to_string(), guidance: "RDR CMD".to_string()},
        "SA-5"      => RwrInfo   { abrv: "SA-5".to_string(),     nato_name: "Gammon".to_string()   ,rwr_code: "5".to_string(),    rng_nm: "190.00".to_string(),  rng_km: "351,88".to_string(),   alt_ft: "115.00".to_string()    ,alt_mtr: "35.050".to_string()  ,flr: "-".to_string() ,chf: "R".to_string() ,ecm: "R".to_string()   ,lock_time: "MED".to_string(), guidance: "CMD SARH".to_string()},
        "SA-6"      => RwrInfo   { abrv: "SA-6".to_string(),     nato_name: "GAINFUL".to_string()  ,rwr_code: "6".to_string(),    rng_nm: "19.20".to_string(),   rng_km: "35,56".to_string(),    alt_ft: "33.000".to_string()    ,alt_mtr: "10.058".to_string()  ,flr: "-".to_string() ,chf: "Y".to_string() ,ecm: "Y".to_string()   ,lock_time: "MED".to_string(), guidance: "CMD SARH".to_string()},
        "SA-8"      => RwrInfo   { abrv: "SA-8".to_string(),     nato_name: "GECKO".to_string()    ,rwr_code: "8".to_string(),    rng_nm: "7.50".to_string(),    rng_km: "13,89".to_string(),    alt_ft: "21.000".to_string()    ,alt_mtr: "6.400".to_string()   ,flr: "-".to_string() ,chf: "G".to_string() ,ecm: "G".to_string() ,lock_time: "MED".to_string(), guidance: "RDR CMD".to_string()},
        "SA-9"      => RwrInfo   { abrv: "SA-9".to_string(),     nato_name: "GASKIN".to_string()   ,rwr_code: "-".to_string(),    rng_nm: "2.50".to_string(),    rng_km: "4,63".to_string(),     alt_ft: "12.000".to_string()    ,alt_mtr: "3.657".to_string()   ,flr: "G".to_string() ,chf: "-".to_string() ,ecm: "-".to_string()   ,lock_time: "FST".to_string(), guidance: "IR".to_string()},
        "SA-10"     => RwrInfo   { abrv: "SA-10".to_string(),    nato_name: "GRUMBLE".to_string()  ,rwr_code: "10".to_string(),   rng_nm: "40.00".to_string(),   rng_km: "74,08".to_string(),    alt_ft: "150.000".to_string()   ,alt_mtr: "45,718".to_string()  ,flr: "-".to_string() ,chf: "R".to_string() ,ecm: "R".to_string()   ,lock_time: "FST".to_string(), guidance: "SARH".to_string()},
        "SA-11"     => RwrInfo   { abrv: "SA-11".to_string(),    nato_name: "GADFLY".to_string()  ,rwr_code: "11".to_string(),   rng_nm: "19.00".to_string(),   rng_km: "35,19".to_string(),    alt_ft: "82.000".to_string()    ,alt_mtr: "24.992".to_string()  ,flr: "-".to_string() ,chf: "R".to_string() ,ecm: "R".to_string()   ,lock_time: "MED".to_string(), guidance: "SARH".to_string()},
        "SA-13"     => RwrInfo   { abrv: "SA-13".to_string(),    nato_name: "GOPHER".to_string()   ,rwr_code: "13".to_string(),   rng_nm: "2.80".to_string(),    rng_km: "5,19".to_string(),     alt_ft: "15.000".to_string()    ,alt_mtr: "4.572".to_string()   ,flr: "Y".to_string() ,chf: "-".to_string() ,ecm: "G".to_string()   ,lock_time: "FST".to_string(), guidance: "IR".to_string()},
        "SA-15"     => RwrInfo   { abrv: "SA-15".to_string(),    nato_name: "GAUNTLET".to_string() ,rwr_code: "15".to_string(),   rng_nm: "6.50".to_string(),    rng_km: "12,04".to_string(),    alt_ft: "26.000".to_string()    ,alt_mtr: "7.924".to_string()   ,flr: "-".to_string() ,chf: "R".to_string() ,ecm: "R".to_string()   ,lock_time: "FST".to_string(), guidance: "RDR OPT".to_string()},
        "SA-18"     => RwrInfo   { abrv: "SA-18".to_string(),    nato_name: "GROUSE".to_string()   ,rwr_code: "-".to_string(),    rng_nm: "2.50".to_string(),    rng_km: "4,63".to_string(),     alt_ft: "12.000".to_string()    ,alt_mtr: "3.657".to_string()   ,flr: "Y".to_string() ,chf: "-".to_string() ,ecm: "-".to_string()   ,lock_time: "FST".to_string(), guidance: "IR".to_string()},
        "SA-19"     => RwrInfo   { abrv: "SA-19".to_string(),    nato_name: "GRINSON".to_string()   ,rwr_code: "S6".to_string(),   rng_nm: "4.00".to_string(),    rng_km: "7,41".to_string(),     alt_ft: "16.000".to_string()    ,alt_mtr: "4.877".to_string()   ,flr: "-".to_string() ,chf: "-".to_string() ,ecm: "R".to_string()   ,lock_time: "FST".to_string(), guidance: "SACLOS".to_string()},
        "SA-24"     => RwrInfo   { abrv: "SA-24".to_string(),    nato_name: "GRINCH".to_string()   ,rwr_code: "-".to_string(),    rng_nm: "3.20".to_string(),    rng_km: "5,93".to_string(),     alt_ft: "12.000".to_string()    ,alt_mtr: "3.657".to_string()   ,flr: "Y".to_string() ,chf: "-".to_string() ,ecm: "-".to_string()   ,lock_time: "FST".to_string(), guidance: "IR".to_string()},
        "ZSU-23-4"  => RwrInfo   { abrv: "ZSU-23-4".to_string(), nato_name: "SHILKA".to_string()   ,rwr_code: "A".to_string(),    rng_nm: "1.30".to_string(),    rng_km: "2,41".to_string(),     alt_ft: "6.500".to_string()     ,alt_mtr: "1.981".to_string()   ,flr: "-".to_string() ,chf: "-".to_string() ,ecm: "-".to_string()   ,lock_time: "FST".to_string(), guidance: "RDR".to_string()},
        "ZSU-23"    => RwrInfo   { abrv: "ZSU-23".to_string(),   nato_name: "SERGEY".to_string()   ,rwr_code: "-".to_string(),    rng_nm: "1.30".to_string(),    rng_km: "2,41".to_string(),     alt_ft: "6.500".to_string()     ,alt_mtr: "1.981".to_string()   ,flr: "-".to_string() ,chf: "-".to_string() ,ecm: "-".to_string()   ,lock_time: "FST".to_string(), guidance: "MK1".to_string()},
        "ZSU-57-2"  => RwrInfo   { abrv: "ZSU-57-2".to_string(), nato_name: "SPARKA".to_string()   ,rwr_code: "-".to_string(),    rng_nm: "6.50".to_string(),    rng_km: "12,04".to_string(),    alt_ft: "15.000".to_string()    ,alt_mtr: "4.572".to_string()   ,flr: "-".to_string() ,chf: "-".to_string() ,ecm: "-".to_string()   ,lock_time: "FST".to_string(), guidance: "MK1".to_string()},
        "GEPARD"    => RwrInfo   { abrv: "Gepard".to_string(),   nato_name: "".to_string()         ,rwr_code: "A".to_string(),    rng_nm: "2.00".to_string(),    rng_km: "3,7".to_string(),      alt_ft: "9.500".to_string()     ,alt_mtr: "2.895".to_string()   ,flr: "-".to_string() ,chf: "-".to_string() ,ecm: "-".to_string()   ,lock_time: "FST".to_string(), guidance: "RDR".to_string()},
        "M163"      => RwrInfo   { abrv: "M163".to_string(),     nato_name: "".to_string()         ,rwr_code: "A".to_string(),    rng_nm: "1.40".to_string(),    rng_km: "2,59".to_string(),     alt_ft: "4.500".to_string()     ,alt_mtr: "1.372".to_string()   ,flr: "-".to_string() ,chf: "-".to_string() ,ecm: "-".to_string()   ,lock_time: "FST".to_string(), guidance: "RDR".to_string()},
        "M1097"     => RwrInfo   { abrv: "M1097".to_string(),    nato_name: "".to_string()         ,rwr_code: "-".to_string(),    rng_nm: "3.70".to_string(),    rng_km: "6,85".to_string(),     alt_ft: "11.000".to_string()    ,alt_mtr: "3.353".to_string()   ,flr: "Y".to_string() ,chf: "-".to_string() ,ecm: "-".to_string()   ,lock_time: "FST".to_string(), guidance: "IR".to_string()},
        "MIM-23"    => RwrInfo   { abrv: "MIM-23".to_string(),   nato_name: "".to_string()         ,rwr_code: "HK".to_string(),   rng_nm: "25.60".to_string(),   rng_km: "47,41".to_string(),    alt_ft: "45.000".to_string()    ,alt_mtr: "13.715".to_string()  ,flr: "-".to_string() ,chf: "Y".to_string() ,ecm: "Y".to_string()   ,lock_time: "MED".to_string(), guidance: "SARH".to_string()},
        _           => RwrInfo   { abrv: "".to_string(),         nato_name: "".to_string()         ,rwr_code: "".to_string(),     rng_nm: "".to_string(),        rng_km: "".to_string(),         alt_ft: "".to_string()          ,alt_mtr: "".to_string()        ,flr: "".to_string()  ,chf: "".to_string()  ,ecm: "".to_string()    ,lock_time: "".to_string(),    guidance: "".to_string()},
    }
}

pub(crate) static PFP_KEYCODES: phf::Map<&'static str, u8> = phf_map! {
    "L1" => 0,
    "L2" => 1,
    "L3" => 2,
    "L4" => 3,
    "L5" => 4,
    "L6" => 5,
    "R1" => 6,
    "R2" => 7,
    "R3" => 8,
    "R4" => 9,
    "R5" => 10,
    "R6" => 11,
    "INIT REF" => 12,
    "RTE" => 13,
    "CLB" => 14,
    "CRZ" => 15,
    "DES" => 16,
    "BRT-" => 17,
    "BRT+" => 18,
    "MENU" => 19,
    "LEGS" => 20,
    "DEP ARR" => 21,
    "HOLD" => 22,
    "PROG" => 23,
    "EXEC" => 24,
    "N1 LIMIT" => 25,
    "FIX" => 26,
    "PREV PAGE" => 27,
    "NEXT PAGE" => 28,
    "1" => 29,
    "2" => 30,
    "3" => 31,
    "4" => 32,
    "5" => 33,
    "6" => 34,
    "7" => 35,
    "8" => 36,
    "9" => 37,
    "." => 38,
    "0" => 39,
    "+-" => 40,
    "A" => 41,
    "B" => 42,
    "C" => 43,
    "D" => 44,
    "E" => 45,
    "F" => 46,
    "G" => 47,
    "H" => 48,
    "I" => 49,
    "J" => 50,
    "K" => 51,
    "L" => 52,
    "M" => 53,
    "N" => 54,
    "O" => 55,
    "P" => 56,
    "Q" => 57,
    "R" => 58,
    "S" => 59,
    "T" => 60,
    "U" => 61,
    "V" => 62,
    "W" => 63,
    "X" => 64,
    "Y" => 65,
    "Z" => 66,
    "SP" => 67,
    "DEL" => 68,
    "/" => 69,
    "CLR" => 70,
};